### ISSUE TITLE
TVDB API - Docs confusing?

### ISSUE THREAD

**Issue by stevezau** [mynttt/UpdateTool#104]
Hi,

The readme says 
```
     # Three items are required to auth with TVDB username, userkey, apikey
     # Supply these as semicolon seperated values. Example: username;DAWIDK9CJKWFJAWKF;e33914feabd52e8192011b0ce6c8
    -e TVDB_API_KEY=tvdbapikey \
```

However, looking at the code and the v4 API.. You only need to supply the PIN from https://thetvdb.com/dashboard/account/subscription.. You don't need to supply the format the readme suggests?

thanks

**Comment by mynttt** [comment]
Hi!

Yes, this is still some really old documentation that needs an update - it is enough when you supply the v4 PIN.

**Comment by mynttt** [comment]
I have removed that part now, thanks for reporting it!
