### ISSUE TITLE
TVDB v4 key won't work, and app no longer accepts legacy key

### ISSUE THREAD

**Issue by SereneScripts** [mynttt/UpdateTool#105]
I updated to the v4 key after v1.7.0 was released.
TVDB shows that the key is active. After inputting the key into the GUI (and or shell, when using docker), I receive this error:

[INFO ] - 2023-02-15 23:32:58 @ TvdbApiV4.auth: Testing TMDB API (v4) pin: xxxxxx-xxxxx-xxxx-xxxx
[ERROR] - 2023-02-15 23:32:58 @ TvdbApiV4.auth: TVDB v4 authorization failed with code 401 and status failure
[ERROR] - 2023-02-15 23:32:58 @ TvdbApiV4.auth: This could be due to the TVDB API v4 having issues at the moment or your credentials being wrong.
[ERROR] - 2023-02-15 23:32:58 @ TvdbApiV4.auth: This is the received response:
[ERROR] - 2023-02-15 23:32:58 @ TvdbApiV4.auth: Payload:{"status":"failure","message":"Unauthorized","data":null}

Credentials haven't changed. I have tried using the old legacy key, the new v4 key, and also the subscriber key and pin. Nothing seems to work.

**Comment by mynttt** [comment]
Hi,

I've reinstated the v3 API so that part is back to like it was before the 1.7.0 update - already pushed a new version with the update. Could you try again with the configuration you had before this issue appeard as it should work now again. Sorry for the inconvinience

**Comment by SereneScripts** [comment]
Thank you for doing this. I am now able to use the updater again.
