### ISSUE TITLE
GUI Application Display Text Issue

### ISSUE THREAD

**Issue by zluckytraveler** [mynttt/UpdateTool#109]
I have the application installed on MacOS using the most recent stable version of java and upon opening the application the display text for the majority of the app is not displaying properly.

<img width="998" alt="Screenshot 2023-06-10 at 1 02 01 PM" src="https://github.com/mynttt/UpdateTool/assets/97180817/272bc6d6-0bbb-4673-ae9f-753bd8e26de5">

**Comment by mynttt** [comment]
That is very strange. I don't have a Mac so I can't debug it. My guess would be either the font is missing or something weird with the DPI scaling is happening.

Anyways, the text labels are not so important and they only have to be set-up once. You could just try to use the screenshot to orientate which field is which.

**Comment by mynttt** [comment]
@zluckytraveler In case you're still interested. I updated the JavaFX runtime today to fix another mac issue; it might have solved this.
