### ISSUE TITLE
Using this with Plex Meta Manager - Don't wipe labels/overlays

### ISSUE THREAD

**Issue by stevezau** [mynttt/UpdateTool#113]
Hi,

I plan to use this with Plex Meta Manager. 

Plex MEta Manager does not use imdb datasets, so this tool is far faster to update the ratings daily.

However, when using this with Plex Meta Manager, this tool removes the labels, etc.
eg
```(Remove) Stripping useless badge data (RT, TMDB, TVDB) for: What Might Be```

Is there any way to tell this tool not to to touch the metadata besides the IMDb rating?

Thanks

**Comment by djonasdev** [comment]
I would also be interested 👍

**Comment by austinarchibald** [comment]
+1 for this. Once I figure out how to use UpdateTool without corrupting my library, I will use both!

**Comment by mynttt** [comment]
This has been implemented with the capability flag `DONT_STRIP_OTHER_RATING_PROVIDERS` with 1.8.2.

https://github.com/mynttt/UpdateTool?tab=readme-ov-file#supply-custom-capability-flags
