### ISSUE TITLE
ISSUE: Set correct plex media server folder (the one with 'Plug-in Support' in it).

### ISSUE THREAD

**Issue by primetime43** [mynttt/UpdateTool#115]
I've added the correct directory for the plex media server folder where the plug-in support folder is and I still get the message. I've used this before and just recently started having issues.

![image](https://github.com/mynttt/UpdateTool/assets/12754111/f256e173-0128-4b2d-aa46-a0f4cb7b3e74)

**Comment by mynttt** [comment]
It's a bit confusing I admit but you have to configure it like in this picture. 

![304565793-f256e173-0128-4b2d-aa46-a0f4cb7b3e74](https://github.com/mynttt/UpdateTool/assets/22261092/6dda464a-34db-4316-905e-4db14be9286f)

**Comment by primetime43** [comment]
@mynttt so I did like you said and I was able to start it, but now I get this issue when its trying to read the libraries. 

[INFO ] - 2024-03-15 16:26:22 @ DatabaseSupport.requestMovieLibraries: Skipping new movie agent library 'Movies' (1) because it does not use imdb as ratings source.

![image](https://github.com/mynttt/UpdateTool/assets/12754111/41436a0b-5f74-4299-8611-c357ad52844b)

**Comment by primetime43** [comment]
I fixed it by going to library settings, advanced, then in there changing the rating source.
