### ISSUE TITLE
Add ability to run on-demand or without scheduling

### ISSUE THREAD

**Issue by keithdsouza** [mynttt/UpdateTool#116]
I think this tool is great, but I don't want to run it continuously. As in, I would want to run this every once in a while through a cron-job (say once a week) or just as an update if I added new items to the library and not have it run as a scheduled job.

Is this something that is possible to do right now or can be added as a future update to this tool?

I don't want a continuous process to run if I can schedule a cronjob for every 12 hours to call the library, where it runs, saves states and then can recover as if the program was exited and then restarted.

**Comment by mynttt** [comment]
It's a useful feature and easy to implement. It's released with 1.8.1. You can supply the capability value `ON_DEMAND` to the tool and it will shutdown after running once.

https://github.com/mynttt/UpdateTool?tab=readme-ov-file#supply-custom-capability-flags

**Comment by keithdsouza** [comment]
Thanks for the quick turnaround, appreciate it
