### ISSUE TITLE
TV Show agent opt-in not working (Unraid)

### ISSUE THREAD

**Issue by nickolasjamesw** [mynttt/UpdateTool#121]
![image](https://github.com/mynttt/UpdateTool/assets/33301696/11ac4a0e-6d5a-446f-8ce8-04595a932dd5)

> Found library [SERIES] TV Shows (ID=2) with agent: tv.plex.agents.series and 4408 item(s).
Found library [SERIES] TV Shows 4K (ID=4) with agent: tv.plex.agents.series and 272 item(s).
New TV Show Agent Library with ID: 2 will not be processed by UpdateTool. Please register with environment variable UNLOCK_FOR_NEW_TV_AGENT to unlock proceessing capabilities.
New TV Show Agent Library with ID: 4 will not be processed by UpdateTool. Please register with environment variable UNLOCK_FOR_NEW_TV_AGENT to unlock proceessing capabilities.

**Comment by mynttt** [comment]
With the new 1.9.0 it dumps the environment variables right at the start. Please let me know if it contains UNLOCK_FOR_NEW_TV_AGENT = 2;4 in there

**Comment by nickolasjamesw** [comment]
> With the new 1.9.0 it dumps the environment variables right at the start. Please let me know if it contains UNLOCK_FOR_NEW_TV_AGENT = 2;4 in there

DUMP OF ENV_VARS: [{PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, RESTART_ON_CRASH=false, **UNLOCK_FOR_NEW_TV_AGENT=**, HOST_CONTAINERNAME=UpdateTool, CAPABILITIES=, TVDB_API_KEY=REDACTED, JVM_MAX_HEAP=256m, TZ=America/Chicago, RUN_EVERY_N_HOURS=12, JAVA_HOME=/usr/local/openjdk-11, OLDPWD=/usr/app, LANG=C.UTF-8, HOST_OS=Unraid, HOSTNAME=d93851757dbd, OVERRIDE_DATABASE_LOCATION=, PLEX_DATA_DIR=/plexdata, JAVA_VERSION=11.0.16, IGNORE_LIBS=, PWD=/config, HOST_HOSTNAME=Tower, SHLVL=1, HOME=/root, _=/usr/local/openjdk-11/bin/java, USE_PLEX_SQLITE_BINARY_FOR_WRITE_ACCESS=/usr/app/plexsqlitedriver/Plex SQLite}]

**Comment by mynttt** [comment]
`UNLOCK_FOR_NEW_TV_AGENT=`

Indicates that the variable is set, however with an empty string. So it looks like the values you have are not passed to the container.

I'd check the configuration for TVDB_API_KEY and compare how it's done there since the value reaches the container.

**Comment by marcherschel** [comment]
For anyone else stumbling onto this issue.

You need to set the value `UNLOCK_FOR_NEW_TV_AGENT=1;2` to the values of tv show agent libraries you want to use (this has historic reasons)

You can validate it by looking in the logs:

```
[INFO ] - 2024-11-01 14:20:10 @ ImdbDockerImplementation.bootstrap: Unlocking library for IMDB TV Show rating update for the new TV Show agent: 1
[INFO ] - 2024-11-01 14:20:10 @ ImdbDockerImplementation.bootstrap: Unlocking library for IMDB TV Show rating update for the new TV Show agent: 2
```

If you now have a library that is not processed it will say:

```
[INFO ] - 2024-11-01 14:20:11 @ ImdbDockerImplementation$ImdbBatchJob.lambda$0: Found library [MOVIE] Movies (ID=3) with agent: tv.plex.agents.movie and 2924 item(s).
[INFO ] - 2024-11-01 14:20:11 @ ImdbDockerImplementation$ImdbBatchJob.lambda$0: Found library [SERIES] TV Shows (ID=6) with agent: tv.plex.agents.series and 13845 item(s).
[INFO ] - 2024-11-01 14:20:11 @ ImdbDockerImplementation$ImdbBatchJob.lambda$2: New TV Show Agent Library with ID: 6 will not be processed by UpdateTool. Please register with environment variable UNLOCK_FOR_NEW_TV_AGENT to unlock proceessing capabilities.
```

so if we set `UNLOCK_FOR_NEW_TV_AGENT=6` we get:

```
[INFO ] - 2024-11-01 14:22:32 @ ImdbDockerImplementation.bootstrap: Unlocking library for IMDB TV Show rating update for the new TV Show agent: 6
...
[INFO ] - 2024-11-01 14:22:32 @ ImdbDockerImplementation$ImdbBatchJob.lambda$3: Will process library TV Shows (ID=6) with agent: tv.plex.agents.series and 13845 item(s).
```

and now it works.
