### ISSUE TITLE
Capabilities error in the GUI tool

### ISSUE THREAD

**Issue by quidnun** [mynttt/UpdateTool#122]
when Capabilities is empty the gui version of the program exits with:

Invalid CAPABILITIES value: Capabilities

the only workaround seems to be to use one of the flags (I was using IGNORE_NO_MATCHING_RESOLVER_LOG or ON_DEMAND)

**Comment by mynttt** [comment]
Are you using version 1.8.2?

**Comment by mynttt** [comment]
Only option I could see this bug happen is: 
 - You launch the software the first time
 - For whatever reason it is unable to cope with the initial state
 - What happens if you remove the value you have added again?

@quidnun
