### ISSUE TITLE
No external id associated with guid

### ISSUE THREAD

**Issue by johanruda** [mynttt/UpdateTool#126]
Hello!

Getting a lot of these errors and not sure where to begin? 

`[ERROR] - 2024-09-16 14:16:00 @ NewPlexAgentToImdbResolvement.resolve: No external id associated with guid plex://season/602e66f533eb76002d61850a (Season 1).`

After a quick google, I think I need to "Fix Match" these in Plex, but I have no idea which season/epidodes these ID's belong to?

Is there a workaround? :)

Thanks!
//Johan

**Comment by marcherschel** [comment]
Hello!

An error like that means that there is no external Id associated with the item in the Plex database.

External id's could be:
- IMDB id
- TVDB id
- TMDB id

For this item there seems to be none of them and thus UpdateTool is unable to do anything with the entry. Currently there is no way to map `plex://season/602e66f533eb76002d61850a` <=> IMDB id by hand in UpdateTool so fix match would be the way to go.

With version 1.9.2 the log message is improved and now shows the full context (Show, Episode (if exists) and season)
