### ISSUE TITLE
TVDB Can't find any associated IMDB ID

### ISSUE THREAD

**Issue by Finch106** [mynttt/UpdateTool#16]
I'm watching the scan on Windows, and it's trying to search for an IMDB ID for every episode rather than the series, is that expected?

[WARN ] - 2020-02-21 16:43:44 @ TvdbToImdbResolvement.resolveEpisode: TVDB item FBI with id 278596/2/1 does not have an IMDB id associated.

**Comment by mynttt** [comment]
Yes that's correct behavior! It tries to update the episodes and the series. Sometimes the episodes have no IMDB id attached so the tool can't work with them and will just ignore them for 14 days.
