### ISSUE TITLE
[Suggestion] Include / Exclude Libraries

### ISSUE THREAD

**Issue by burkasaurusrex** [mynttt/UpdateTool#17]
I though it might be cool to have an env variable to exclude certain libraries (I have some TV libraries of things that will never be on IMDB for example)

**Comment by mynttt** [comment]
Sounds like a good idea! I'll look into it tomorrow.

**Comment by mynttt** [comment]
Option is now implemented with the [IGNORE_LIBS](https://github.com/mynttt/UpdateTool#other-configuration-values) environment variable.

**Comment by burkasaurusrex** [comment]
This is awesome by the way - thanks so much!
