### ISSUE TITLE
No libraries found

### ISSUE THREAD

**Issue by mraniki** [mynttt/UpdateTool#20]
I'm using the docker component on linux https://hub.docker.com/r/mynttt/updatetool
The tool is only able to identify my TV library when the TVDB option environment  is activated and got all the imdb ratings. but for movie it doesn't identify any library. below the logs when i deactivate the tvdb option.

**** Invoking tool! Logs in /config ****
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Running version: 1.3.5
[INFO ] - 2020-03-21 10:31:39 @ Main.testApiTmdb: Testing TMDB API key: xremovedx
[INFO ] - 2020-03-21 10:31:39 @ Main.genericApiTest: Test passed. API Key is valid.
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: TMDB API key enabled TMDB <=> IMDB matching. Will fetch IMDB ratings for non matched IMDB items.
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: No TVDB API authorization string detected. Will not attempt to update IMDB ratings for TV Series with the TVDB agent.
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Starting IMDB Watchdog
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Plex data dir: /plexdata
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Invoke every 12 hour(s)
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Running first task...
[INFO ] - 2020-03-21 10:31:39 @ ImdbDockerImplementation.invoke: Scheduling next tasks to run @ every 12 hour(s)
[INFO ] - 2020-03-21 10:31:40 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
[INFO ] - 2020-03-21 10:31:40 @ ImdbDockerImplementation$ImdbBatchJob.run: No libraries found. Sleeping until next invocation...

**Comment by mynttt** [comment]
This tool only looks for movie libraries that use the Plex movie agent and have IMDB as rating source. 

This is by design to not accidentally override ratings provided by custom agents or replace Rotten Tomatoes ratings with IMDB ones.

```sql
SELECT id, name FROM library_sections WHERE agent = 'com.plexapp.agents.imdb';
```

If you run the above query on your Plex database it should list the libraries that qualify. 

You can change the agent by going into the advanced library settings and setting the agent to 'Plex Movie' and rating source to 'IMDB'.

![a1](https://user-images.githubusercontent.com/22261092/77235044-efd0a300-6bb2-11ea-9476-e9d9a4dcd45d.PNG)
![a2](https://user-images.githubusercontent.com/22261092/77235045-f0693980-6bb2-11ea-9c13-47a4dae4071a.PNG)

**Comment by mraniki** [comment]
Ok so that must be my problem, I do have IMDB rating for plex movie agent and i have plex movie in the TMDB agent but  my library is using TMDB instead of plex movie. So plex movie needs to be used as main agent not sub agent ?

![Screen Shot 2020-03-21 at 4 20 50 PM](https://user-images.githubusercontent.com/8766259/77235873-f4379480-6b8f-11ea-8e6e-dd2ae3c2a2b1.png)


![Screen Shot 2020-03-21 at 4 19 16 PM](https://user-images.githubusercontent.com/8766259/77235863-cfdbb800-6b8f-11ea-8546-5d6621847987.png)

**Comment by mraniki** [comment]
I'm updating to main agent (instead of subagent) and will keep you posted @mynttt

**Comment by mynttt** [comment]
Yeah I kind of forgot that agents can also be configured via that page. 

The screenshots I shared were from the library specific settings which can be reached like this.

![u](https://user-images.githubusercontent.com/22261092/77236214-e6e4cf00-6bbc-11ea-99d9-1d8a19582d6a.png)

If everything fails for you I can take a look at whats inside the database to get a better understanding.

You would just have to run this on the plex database and upload the export.csv to this issue:

```bash
sqlite3 com.plexapp.plugins.library.db <<EOF
.mode csv
.output export.csv
SELECT * FROM library_sections WHERE section_type = 1;
EOF
```

**Comment by mraniki** [comment]
Thanks @mynttt . I will switch to main agent tomorrow but i attached the export of current setup with TMDB as agent and plex movie as sub agent with IMDB.

**Comment by mynttt** [comment]
Let me know how it works out for you!

**Comment by mraniki** [comment]
Worked like a charmed for movie library after updating the agent. Great tool. Series and Movies up to date. Is the docker monitoring and updating every 12 hours automatically ?

**Comment by mynttt** [comment]
Glad it worked! Tool will run over the libraries every 12h now. IMDB dataset is refreshed every 2 days as far as I remember.

Resolved IDs have been cached so the tool is know blazingly fast as long as it doesn't need to resolve a bunch of IDs over an external API.
