### ISSUE TITLE
thetvdb userkey

### ISSUE THREAD

**Issue by Septan** [mynttt/UpdateTool#23]
I wanted to try out your tool, I stuck where I suppose to username and user key for the TVB. I can't find anymore on do get my user key. How can get it?

**Comment by mynttt** [comment]
I just looked at it, looks like the TVDB site currently doesn't allow to display your user key for some reason.

The API key alone is sufficient apparently. I will patch the tool today to only require the API for the TVDB API.

I'll post here again once it's patched.

**Comment by mynttt** [comment]
Instead of TVDB_AUTH_STRING you can now use the TVDB_API_KEY variable and only have to add your TVDB api key.
