### ISSUE TITLE
Since Last Plex Agent Update

### ISSUE THREAD

**Issue by Marty605** [mynttt/UpdateTool#34]
Not working since last plex agent update 

[INFO ] - 2020-08-31 20:43:49 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
[INFO ] - 2020-08-31 20:43:49 @ ImdbDockerImplementation$ImdbBatchJob.run: No libraries found. Sleeping until next invocation...

**Comment by mynttt** [comment]
Thats strange. To investigate this issue you would have to dump your library data and upload it here. You can use this command to do that via sqlite:

```bash
sqlite3 com.plexapp.plugins.library.db ".mode csv" ".headers on" "SELECT * FROM library_sections;" > out.csv
```

Then attach the out.csv to this issue.

**Comment by Marty605** [comment]
> Thats strange. To investigate this issue you would have to dump your library data and upload it here. You can use this command to do that via sqlite:
> 
> ```shell
> sqlite3 com.plexapp.plugins.library.db ".mode csv" ".headers on" "SELECT * FROM library_sections;" > out.csv
> ```
> 
> Then attach the out.csv to this issue.

Working now just need to refresh all library metadata
