### ISSUE TITLE
Updatetool error 

### ISSUE THREAD

**Issue by BrodyBuster** [mynttt/UpdateTool#37]
running update tool in docker using docker compose:

'updatetool:
    image: mynttt/updatetool
    container_name: updatetool
    environment:
      - RUN_EVERY_N_HOURS=1
      - TMDB_API_KEY=<<#valid key#>>
    volumes:
      - /opt/appdata/plex/config/Library/Application Support/Plex Media Server:/plexdata:rw
      - /opt/appdata/plexupdate/config:/config:rw
    network_mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"'

receiving the following error:
`**** Invoking tool! Logs in /config ****
[INFO ] - 2020-09-09 12:53:33 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
[INFO ] - 2020-09-09 12:53:33 @ Main.main: Running version: 1.4.3
[INFO ] - 2020-09-09 12:53:33 @ Main.main: Args: {imdb-docker={schedule=1}}
[INFO ] - 2020-09-09 12:53:33 @ Main.main: << INIT: imdb-docker @ {schedule=1} >>
[INFO ] - 2020-09-09 12:53:33 @ Main.testApiTmdb: Testing TMDB API key: <<#valid key#>>
[INFO ] - 2020-09-09 12:53:34 @ Main.genericApiTest: Test passed. API Key is valid.
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation.bootstrap: TMDB API key enabled TMDB <=> IMDB matching. Will process TMDB backed Movie and TV Series libraries and TMDB orphans.
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation.bootstrap: No TVDB API authorization string detected. Will process TVDB backed TV Series libraries.
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation.bootstrap: Starting IMDB Watchdog
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation.bootstrap: Plex data dir: /plexdata
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation.bootstrap: Capabilities: [TMDB]
[INFO ] - 2020-09-09 12:53:34 @ Main.main: << INIT SUCCESS >>
[INFO ] - 2020-09-09 12:53:34 @ Scheduler.go: Scheduler is loading tasks... Blocking until completely set-up and ready to go.
[INFO ] - 2020-09-09 12:53:34 @ Scheduler.go: Scheduling tasks...
[INFO ] - 2020-09-09 12:53:34 @ Scheduler.lambda$go$0: Scheduled imdb-docker task to run @ every 1 hour(s).
[INFO ] - 2020-09-09 12:53:34 @ Scheduler.lambda$go$1: Queued task imdb-docker for immediate execution.
[INFO ] - 2020-09-09 12:53:34 @ Scheduler.go: Running supplied tasks immediately NOW!
[INFO ] - 2020-09-09 12:53:34 @ TaskWrapper.run: ================================================
[INFO ] - 2020-09-09 12:53:34 @ TaskWrapper.run: Starting task: imdb-docker | Execution count: 0
[INFO ] - 2020-09-09 12:53:34 @ TaskWrapper.run: ================================================
[INFO ] - 2020-09-09 12:53:34 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
[INFO ] - 2020-09-09 12:53:34 @ ImdbRatingDatasetFactory.readData: Reading data...
[INFO ] - 2020-09-09 12:53:36 @ ImdbRatingDatasetFactory.readData: 1071419 lines read.
[INFO ] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Movies has 2067 item(s)
[INFO ] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: Processing [MOVIE] Movies with UUID cb9402b2-ed35-4a2f-a285-1e4e5df18564 at stage: CREATED
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.analyseDatabase: Resolving IMDB identifiers for items. Only warnings and errors will show up...
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.analyseDatabase: Items that show up here will not be processed by further stages of the pipeline.
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.analyseDatabase: Filtered 0 invalid item(s).
[WARN ] - 2020-09-09 12:53:36 @ ImdbTransformer.needsUpdate: Ignoring: 'Mia and the White Lion' with IMDB ID: tt6249748 supplies no valid rating := 'null'
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.transformMetadata: 2038 item(s) need no update.
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.transformMetadata: Transforming 29 item(s)
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 5.4 -> 5.3 for Sniper: Assassin's End
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.6 -> 6.7 for Scooby-Doo! Pirates Ahoy!
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.0 -> 7.1 for Scooby-Doo! Abracadabra-Doo
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 8.0 -> 7.9 for X-Men: Days of Future Past
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 4.8 -> 4.9 for Fearless
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.5 -> 7.4 for Palm Springs
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.2 -> 7.0 for Class Action Park
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 3.8 -> 5.6 for Mulan
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.6 -> 6.5 for Sonic the Hedgehog
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: null -> 7.0 for I'm Thinking of Ending Things
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: I'm Thinking of Ending Things
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: I'm Thinking of Ending Things
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.3 -> 6.4 for The Personal History of David Copperfield
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.1 -> 2.9 for Hard Kill
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 5.7 -> 5.6 for Jungle Beat: The Movie
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 8.1 -> 6.4 for Bill & Ted Face the Music
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 8.1 -> 8.0 for Rudolph the Red-Nosed Reindeer
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 2.5 -> 4.6 for The Owners
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: The Owners
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.8 -> 6.9 for Teen Titans Go! vs. Teen Titans
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.2 -> 6.1 for Rambo: Last Blood
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 5.9 -> 3.8 for Rogue
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Rogue
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Rogue
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 2.0 -> 4.9 for One Night in Bangkok
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: One Night in Bangkok
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.3 -> 6.2 for Ocean's Eight
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.7 -> 7.8 for Boyz n the Hood
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.4 -> 6.8 for The Call of the Wild
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: The Call of the Wild
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.1 -> 6.2 for The Jewel of the Nile
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 8.6 -> 7.3 for Phineas and Ferb the Movie: Candace Against the Universe
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Phineas and Ferb the Movie: Candace Against the Universe
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Phineas and Ferb the Movie: Candace Against the Universe
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.0 -> 6.1 for Dora and the Lost City of Gold
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.9 -> 7.0 for Bill & Ted's Excellent Adventure
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 7.8 -> 7.7 for Blue Velvet
[INFO ] - 2020-09-09 12:53:36 @ ImdbTransformer.updateMetadata: Adjust rating: 6.1 -> 6.0 for San Andreas
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.transformMetadata: Transformed entries for 29 items(s).
[INFO ] - 2020-09-09 12:53:36 @ ImdbPipeline.updateDatabase: Updating 29 via batch request...
[INFO ] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned ERROR : No message specified.
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: NullPointerException exception encountered...
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: java.lang.NullPointerException
	at updatetool.imdb.ImdbDatabaseSupport.requestBatchUpdateOf(ImdbDatabaseSupport.java:142)
	at updatetool.imdb.ImdbPipeline.updateDatabase(ImdbPipeline.java:180)
	at updatetool.imdb.ImdbPipeline.updateDatabase(ImdbPipeline.java:48)
	at updatetool.api.Pipeline.invoke(Pipeline.java:26)
	at updatetool.imdb.ImdbJobRunner.run(ImdbJobRunner.java:19)
	at updatetool.imdb.ImdbDockerImplementation$ImdbBatchJob.run(ImdbDockerImplementation.java:233)
	at updatetool.TaskWrapper.run(Main.java:284)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2020-09-09 12:53:36 @ ImdbDockerImplementation$ImdbBatchJob.run: The application will terminate now.'

thanks

**Comment by BrodyBuster** [comment]
Plex is using the new PLEX MOVIE agent

**Comment by mynttt** [comment]
I have no idea what causes the error. At that point the value should not be null and cause that NPE there. To fix it I've added a mitigation that skips such entries and logs an error with the associated entry, so we can investigate further. Make sure to update your docker to get the version with the hotfix.

Start the tool again and see if you find such an entry in the logfile: 
```Null value encountered. Should not be possible. Skipping entry to not crash tool. Contact maintainer with this dump```

If so post the dump in here so we can investigate further.
