### ISSUE TITLE
Match TMDb series even if TVDb API key not set.

### ISSUE THREAD

**Issue by wogam** [mynttt/UpdateTool#39]
Hi, firstly thank you so much for creating this tool - it really is a marvel.

I was wondering if it would be possible to allow shows to be processed which have TVDb set as the library type, but have been matched with TMDb. This would be useful for those without an API key for TVDb (especially since it will be deprecated in early 2021). Currently, TV shows will only be processed via TMDb if TMDb is set as the library agent.

**Comment by mynttt** [comment]
So you mean like libraries that use the TVDB agent but have some older entries that are matched via TMDB? Could you describe the issue a bit clearer for me? I have a hard time right now understanding the request.

**Comment by wogam** [comment]
@mynttt Yes that's correct. I have a Library with TVDb as the agent, but around half the shows were matched earlier with TMDb. There's no way to match/update ratings on these shows.

**Comment by mynttt** [comment]
But you have a TMDB API key set? Normally it should also consider all items that have an agent resolver, but I belive this is only done for movies. I'll look into it tomorrow and change it so it resolves both.

**Comment by wogam** [comment]
Yeh, I do have a TMDb api key set. Let know whenever you do it and I will give it a test.

**Comment by mynttt** [comment]
It would be helpfull if you could send me your plex database. I just looked onto my server and all my entries are TVDB matched. I need some sample data to reproduce your issue. If you don't want to publicly post it here you can send a mail to marc@herschel.io

**Comment by mynttt** [comment]
Closed due to inactivity.
