### ISSUE TITLE
IllegalStateException exception encountered

### ISSUE THREAD

**Issue by ookla-ariel-ride** [mynttt/UpdateTool#4]
I am getting the following error on my system (Ubuntu 18.04.3 w/openjdk 11)

[INFO ] - 2019-12-29 03:37:34 @ ImdbPipeline.accumulateMetadata: Items: 14481
[INFO ] - 2019-12-29 03:37:34 @ ImdbPipeline.accumulateMetadata: Metadata missing for: 240
[INFO ] - 2019-12-29 03:37:34 @ ImdbPipeline.accumulateMetadata: Retrieving metadata...
[INFO ] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned ERROR : null
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: IllegalStateException exception encountered...
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: java.lang.IllegalStateException: API call failed with code 200: {"Response":"False","Error":"Error getting data."}
        at updatetool.imdb.ImdbOmdbWorker.call(ImdbOmdbWorker.java:68)
        at updatetool.imdb.ImdbOmdbWorker.call(ImdbOmdbWorker.java:16)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2019-12-29 03:37:36 @ ImdbDockerImplementation$ImdbBatchJob.run: The application will terminate now.

**Comment by mynttt** [comment]
Extremely interesting! The OMDB Api has one problem: it's sends out HTTP Status code 200 even when a request failed. The response boolean is their way of saying something went wrong instead of just sending something in the 500+ range.

I think if you run it again it should work fine again. I will update the retry loop tho to handle this special case and fail with a more descriptive message. Thanks for submitting!

**Comment by mynttt** [comment]
Closed with 88d7fdabb9008a809daeb04b27344353050f040f
