### ISSUE TITLE
Revert Changes to TV Show Libraries

### ISSUE THREAD

**Issue by nplat** [mynttt/UpdateTool#45]
This works perfectly for movies (thank you!), but ratings completely disappear for TV shows in Plex IOS apps. Is there a way to revert the changes in order to remove IMDB ratings from the TV Show libraries?

**Comment by mynttt** [comment]
There is no way to revert anything that this tool has done other than restoring a database backup.

I've been contacted by another user via the Plex forums a few months ago that had similar issues regarding iOS devices. There is also a thread about it [here](https://forums.plex.tv/t/imdb-ratings-missing-from-plex-apple-devices/631771).

It appears that the iOS app is at fault here as the web interface and the Android versions work flawlessly. This also means that Plex has to release a fix for iOS.
