### ISSUE TITLE
DB field to be updated

### ISSUE THREAD

**Issue by oleroc** [mynttt/UpdateTool#46]
Hi.
I noticed now that Plex is using Audience rating instead of Critic Rating when populating the Score field. Will you change update tool to use this field as well? IMDB score is an audience score after all.

**Comment by mynttt** [comment]
This is currently supported for the new Plex Movie Agent but not for the older legacy agents and I will probably not change it as these older agents behave the same (using the rating field for everything). 

The tool currently behaves this way:

https://github.com/mynttt/UpdateTool/blob/65f4335a54cbaaace2e418b3220ee9a0cccd014b/src/main/java/updatetool/imdb/ImdbDatabaseSupport.java#L139-L140

**New Agent**: Inserting IMDB ratings into the audience score and nulling the critic rating (none exists for IMDB ratings).
**Old Agents**: Inserting IMDB ratings into the normal score field as that was the observed behavior of those agents as well and changing it might cause issues when displaying the ratings in the UI.
