### ISSUE TITLE
Not processing TV shows? 

### ISSUE THREAD

**Issue by burpfish** [mynttt/UpdateTool#47]
Thx for this - it's awesome!

For me, with a TMDB key (but no TVDB key), it works for movies but not for TV.
Are there any settings I need to check w/ Plex agents?
Thx in advance!

My logs:
imdb-update       | **** Invoking tool! Logs in /config ****
imdb-update       | [INFO ] - 2020-12-17 16:32:57 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
imdb-update       | [INFO ] - 2020-12-17 16:32:57 @ Main.main: Running version: 1.4.5
imdb-update       | [INFO ] - 2020-12-17 16:32:57 @ Main.main: Args: {imdb-docker={schedule=12}}
imdb-update       | [INFO ] - 2020-12-17 16:32:57 @ Main.main: << INIT: imdb-docker @ {schedule=12} >>
imdb-update       | [INFO ] - 2020-12-17 16:32:57 @ Main.testApiTmdb: Testing TMDB API key: xxxxxxxxxxxxxxxxxxxxx
imdb-update       | [INFO ] - 2020-12-17 16:32:58 @ Main.genericApiTest: Test passed. API Key is valid.
imdb-update       | [INFO ] - 2020-12-17 16:32:58 @ ImdbDockerImplementation.bootstrap: TMDB API key enabled TMDB <=> IMDB matching. Will process TMDB backed Movie and TV Series libraries and TMDB orphans.
imdb-update       | [INFO ] - 2020-12-17 16:32:58 @ ImdbDockerImplementation.bootstrap: No TVDB API authorization string detected. Will process TVDB backed TV Series libraries.
imdb-update       | [INFO ] - 2020-12-17 16:32:58 @ ImdbDockerImplementation.bootstrap: Starting IMDB Watchdog
imdb-update       | [INFO ] - 2020-12-17 16:32:58 @ ImdbDockerImplementation.bootstrap: Plex data dir: /plexdata
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ ImdbDockerImplementation.bootstrap: Capabilities: [TMDB, VERBOSE_XML_ERROR_LOG]
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Main.main: << INIT SUCCESS >>
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Scheduler.go: Scheduler is loading tasks... Blocking until completely set-up and ready to go.
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Scheduler.go: Scheduling tasks...
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Scheduler.lambda$go$0: Scheduled imdb-docker task to run @ every 12 hour(s).
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Scheduler.lambda$go$1: Queued task imdb-docker for immediate execution.
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ Scheduler.go: Running supplied tasks immediately NOW!
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ TaskWrapper.run: ================================================
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ TaskWrapper.run: Starting task: imdb-docker | Execution count: 0
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ TaskWrapper.run: ================================================
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ ImdbDatabaseSupport.updateNewAgentMetadataMapping: Associated and cached tmdb://567604 with new movie agent guid plex://movie/5d7770a996b655001fe9bc1d (Once Upon a Deadpool).
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
imdb-update       | [INFO ] - 2020-12-17 16:32:59 @ ImdbRatingDatasetFactory.readData: Reading data...
imdb-update       | [INFO ] - 2020-12-17 16:33:04 @ ImdbRatingDatasetFactory.readData: 1103064 lines read.
imdb-update       | [INFO ] - 2020-12-17 16:33:04 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Movies has 1438 item(s)
imdb-update       | [INFO ] - 2020-12-17 16:33:04 @ ImdbDockerImplementation$ImdbBatchJob.run: Processing [MOVIE] Movies with UUID ac7f1eb0-517e-4971-bc32-60d0180f526d at stage: CREATED
imdb-update       | [INFO ] - 2020-12-17 16:33:04 @ ImdbPipeline.analyseDatabase: Resolving IMDB identifiers for items. Only warnings and errors will show up...
imdb-update       | [INFO ] - 2020-12-17 16:33:04 @ ImdbPipeline.analyseDatabase: Items that show up here will not be processed by further stages of the pipeline.
imdb-update       | [WARN ] - 2020-12-17 16:33:04 @ DefaultResolvement.resolve: Item: 'Classic Albums Pink Floyd the Dark Side of the Moon' has no matching IMDB resolver and will be ignored. (guid=local://1058)
imdb-update       | [WARN ] - 2020-12-17 16:33:05 @ TmdbMovieToImdbResolvement.lambda$new$1: TMDB Movie item Once Upon a Deadpool with id 567604 does not have an IMDB id associated.
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.analyseDatabase: Filtered 2 invalid item(s).
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.transformMetadata: 1389 item(s) need no update.
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.transformMetadata: Transforming 0 item(s)
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.transformMetadata: Transformed entries for 0 items(s).
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.updateDatabase: Nothing to update. Skipping...
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.updateXML: Updating XML fallback files for 0 item(s).
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbPipeline.updateXML: Completed updating of XML fallback files.
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned PASS : Job finished correctly
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbDockerImplementation$ImdbBatchJob.run: Job finished successfully for [MOVIE] Movies with UUID ac7f1eb0-517e-4971-bc32-60d0180f526d
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ ImdbDockerImplementation$ImdbBatchJob.run: Completed batch successfully.
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ TaskWrapper.run: ================================================
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ TaskWrapper.run: Suggesting JVM to run the GC as soon as possible (Request might be ignored!)
imdb-update       | [INFO ] - 2020-12-17 16:33:05 @ TaskWrapper.run: Completed imdb-docker in 6.55288s. - Invoking next task or going to sleep. It is safe to suspend execution if no other task is being invoked immediately.

**Comment by mynttt** [comment]
I suspect that your TV show libraries are using the TVDB agent and are ignored because of your missing TVDB api key.

To confirm this you can run this sqlite3 query on your plex database and post the output here:

```sql
SELECT name, agent FROM library_sections;
```

**Comment by mynttt** [comment]
Closed due to inactivity.
