### ISSUE TITLE
request to contact developer

### ISSUE THREAD

**Issue by owanneke** [mynttt/UpdateTool#50]
As to your own request I guess :-)

[WARN ] - 2021-02-02 04:13:45 @ NewPlexMovieAgentToImdbResolvement.resolve: Unhandled external id (tvdb://132869). Please contact the author of the tool.

[WARN ] - 2021-02-02 04:13:45 @ NewPlexMovieAgentToImdbResolvement.resolve: Unhandled external id (tvdb://93322). Please contact the author of the tool.

**Comment by mynttt** [comment]
Seems like it can also add TVDB entries there on its own. I'll look into it after my exams are over.

**Comment by mynttt** [comment]
Next update will include a resolvement of those IDs.

**Comment by mynttt** [comment]
Implemented with 1.5.1
