### ISSUE TITLE
Rating feature request

### ISSUE THREAD

**Issue by owanneke** [mynttt/UpdateTool#51]
Not sure if this is the right place to request, but I couldn't find anywhere else.

I would love to see an option to select Metacritic ratings as source.
Maybe even store them in the "critics rating", as that's not used when using IMDB as source and sorting by it, sorts by title.

**Comment by mynttt** [comment]
I think this is not possible as the point of failure here is matching the correct Metacritic items. Neither TMDB not TVDB even have a metacritic field and even if they had it, it would likely not be populated for many items.

Another issue is that it won't be possible to display a custom icon as Plex does not support a Metacritic icon like they do with TMDB/TVDB/IMDB. I belive that this request is currently out of scope.
