### ISSUE TITLE
TMDB messages

### ISSUE THREAD

**Issue by owanneke** [mynttt/UpdateTool#53]
Feature request: 

Can TMDB messages be omitted from the output if no TMDB resolvement is enabled and only keep the message TMDB is not enabled?
Repeating the same hundreds of messages on each run for movies that do not exist in IMDB when TMDB is not is use makes the logs hard to read.

[WARN ] - 2021-03-13 07:37:32 @ NewPlexAgentToImdbResolvement.resolve: TMDB id associated with new plex MOVIE agent guid but no TMDB resolvement enabled. Ignoring item: (tmdb://82419, plex://movie/5d77702147dd6e001f707d62, Queen: Live Aid)

**Comment by owanneke** [comment]
created fork with proposed change

**Comment by mynttt** [comment]
Has been removed, will be corperated into the next future update.
