### ISSUE TITLE
no valid rating when rating available

### ISSUE THREAD

**Issue by owanneke** [mynttt/UpdateTool#54]
Message

[WARN ] - 2021-03-12 18:37:35 @ ImdbTransformer.needsUpdate: Ignoring: 'Queen: Live at the Rainbow' with IMDB ID: tt4135970 supplies no valid rating := 'null'

Yet IMDB shows rating of 8.4 with 203 votes.

**Comment by mynttt** [comment]
Seems like IMDB does not include this rating within their exported data set. If you search the rating_set.tsv for tt4135970 it will yield no result and is thus not reachable for UpdateTool. Adding a screen scraping module for such egde cases seems to be an overkill solution for such a rare edge case. Usually IMDB will include the rating after some time in a newly downloaded dataset.
