### ISSUE TITLE
TVDb v3 

### ISSUE THREAD

**Issue by burkasaurusrex** [mynttt/UpdateTool#55]
I'm having issues trying to use TVDb v3 still? It looks like my TVDb v3 creds pass but then the TVDb v4 failed test stops the container

```
*** VERSION 1.5.3 IS UP TO DATE! ***

MAX JVM HEAP: -Xmx256m
**** Invoking tool! Logs in /config ****
[INFO ] - 2021-03-17 10:51:56 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
[INFO ] - 2021-03-17 10:51:56 @ Main.main: Running version: 1.5.3

[INFO ] - 2021-03-17 10:51:56 @ Main.main: Args: {imdb-docker={schedule=12}}
[INFO ] - 2021-03-17 10:51:56 @ Main.main: << INIT: imdb-docker @ {schedule=12} >>
[INFO ] - 2021-03-17 10:51:56 @ TmdbApiV3.<init>: Testing TMDB API (v3) key: *****
[INFO ] - 2021-03-17 10:51:56 @ TmdbApiV3.<init>: Test passed. API Key is valid.
[INFO ] - 2021-03-17 10:51:56 @ ImdbDockerImplementation.bootstrap: TMDB API key enabled TMDB <=> IMDB matching. Will process TMDB backed Movie and TV Series libraries and TMDB orphans.
[INFO ] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: Testing TMDB API (v4) pin: *****
[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: TVDB v4 authorization failed with code 401 and status failure

[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: This could be due to the TVDB API v4 having issues at the moment or your credentials being wrong.

[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: This is the received response:

[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: Payload:{"status":"failure","message":"InvalidAPIKey: pin invalid","data":null}


[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: Pin (v4) available under: https://www.thetvdb.com

[ERROR] - 2021-03-17 10:51:56 @ TvdbApiV4.auth: ===================================================
```

**Comment by mynttt** [comment]
Did you set the 32 character long TVDB v3 API Key or something else?

**Comment by burkasaurusrex** [comment]
I've tried both (the shorter older API key and the newer 32 char key) with the same result

**Comment by mynttt** [comment]
Please send the API Keys that you tried to my email. I have to see them to make any diagnose here.

**Comment by dazedcrazy** [comment]
Any update to this?

**Comment by mynttt** [comment]
@dazedcrazy If you have the same issue send your API key to marc@herschel.io. Without seeing your input I can't fix this, there might be a bug thaf I'm now aware of atm.

**Comment by dazedcrazy** [comment]
I just went back to using 1.5.1. TVDb will be disabling v3 API keys soon anyway and hopefully Plex will have added IMDb ratings to the new TV Scanner by then. I use my API Key in another program daily and don't want to risk it getting disabled early by giving it out.

**Comment by dazedcrazy** [comment]
I this was closed because no key was given for you to test but https://github.com/mynttt/UpdateTool/commit/6ec904672d8d72201afbb1944f47fbeba5e642e0 now fixes this issue.

**Comment by mynttt** [comment]
@dazedcrazy I'm glad it works for you now! If you compare these two tickets you'll see that the one that lead to the fix described the key perfectly. This was required to actually fix the problem.
