### ISSUE TITLE
New errors with docker implementation

### ISSUE THREAD

**Issue by ookla-ariel-ride** [mynttt/UpdateTool#58]
I recently started getting these errors:

I am running the latest docker version (updated with watchtower)

*** VERSION 1.5.4 IS UP TO DATE! ***
,MAX JVM HEAP: -Xmx2g
,**** Invoking tool! Logs in /config ****
,Error: Unable to access jarfile /usr/app/tool.jar
,*** VERSION 1.5.4 IS UP TO DATE! ***
,MAX JVM HEAP: -Xmx2g
,**** Invoking tool! Logs in /config ****
,Error: Unable to access jarfile /usr/app/tool.jar
,*** VERSION 1.5.4 IS UP TO DATE! ***
,MAX JVM HEAP: -Xmx2g
,**** Invoking tool! Logs in /config ****
,Error: Unable to access jarfile /usr/app/tool.jar
,*** VERSION 1.5.4 IS UP TO DATE! ***
,MAX JVM HEAP: -Xmx2g
,**** Invoking tool! Logs in /config ****
,Error: Unable to access jarfile /usr/app/tool.jar
,*** VERSION 1.5.4 IS UP TO DATE! ***
,MAX JVM HEAP: -Xmx2g
,**** Invoking tool! Logs in /config ****
,Error: Unable to access jarfile /usr/app/tool.jar
,

**Comment by mynttt** [comment]
There was a fail docker that was only available for a few minutes. I guess it is that one, can you try again to update your docker?

**Comment by ookla-ariel-ride** [comment]
ok, recreated the docke and now it is working.  thanks.
