### ISSUE TITLE
API call failed with code 200 after + 5 attempt(s)

### ISSUE THREAD

**Issue by ookla-ariel-ride** [mynttt/UpdateTool#6]
I am still getting errors running this.  

[INFO ] - 2020-01-02 01:31:16 @ ImdbPipeline.analyseDatabase: Filtered 46 invalid item(s).
[INFO ] - 2020-01-02 01:31:16 @ ImdbPipeline.accumulateMetadata: Items: 14489
[INFO ] - 2020-01-02 01:31:16 @ ImdbPipeline.accumulateMetadata: Metadata missing for: 24
[INFO ] - 2020-01-02 01:31:16 @ ImdbPipeline.accumulateMetadata: Retrieving metadata...
[WARN ] - 2020-01-02 01:31:16 @ ImdbOmdbWorker.call: OMDB API returned a reply with status code 200 but the reply is invalid. Trying again... 1/5
[WARN ] - 2020-01-02 01:31:16 @ ImdbOmdbWorker.call: OMDB API returned a reply with status code 200 but the reply is invalid. Trying again... 2/5
[WARN ] - 2020-01-02 01:31:16 @ ImdbOmdbWorker.call: OMDB API returned a reply with status code 200 but the reply is invalid. Trying again... 3/5
[WARN ] - 2020-01-02 01:31:16 @ ImdbOmdbWorker.call: OMDB API returned a reply with status code 200 but the reply is invalid. Trying again... 4/5
[WARN ] - 2020-01-02 01:31:16 @ ImdbOmdbWorker.call: OMDB API returned a reply with status code 200 but the reply is invalid. Trying again... 5/5
[INFO ] - 2020-01-02 01:31:17 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned API_ERROR : Aborted job queue due to the API failing to deliver a result.
[ERROR] - 2020-01-02 01:31:17 @ ImdbDockerImplementation$ImdbBatchJob.run: Aborted job queue due to the API failing to deliver a result.
[ERROR] - 2020-01-02 01:31:17 @ ImdbDockerImplementation$ImdbBatchJob.run: Original message: API call failed with code 200 after + 5 attempt(s): {"Response":"False","Error":"Error getting data."}

**Comment by mynttt** [comment]
Thats on OMDBs side. I will change the tool to just cancel any activity at the moment and just sleep for N hours if that happens and not terminate the runtime.

**Comment by mynttt** [comment]
Closed with 8e3fdb26851399f5cdb29f7b9f5c48bbfe6351ce
