### ISSUE TITLE
TV library id's end with "&context=library%3Acontent.library~0~1" not "&context=content.library&source=1"

### ISSUE THREAD

**Issue by mattgorski** [mynttt/UpdateTool#67]
I would like to try out your fantastic tool but before I corrupt my PMS database I would like to know if the new id's will still work.  When I click on a TV series the URL ends with id's as the title says:

`&context=library%3Acontent.library~0~1`

Not

`&context=content.library&source=1`

Will your tool still work?

Would i use this flag: `UNLOCK_FOR_NEW_TV_AGENT="~0~0;~0~1"`

Side note:  Can I backup the "com.plexapp.plugins.library.db" and restore if any corruption occurs after running your tool?

**Comment by mattgorski** [comment]
You can close/delete this issue I noticed the library was just the complete library not per series.

**Comment by mynttt** [comment]
To add to this: Yes, you can do a backup and restore without issues in case anything happens! Plex should also create scheduled backups automatically as well.

At the start of the tool the log also contains the library IDs which is an easier way to aquire them:

```
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.run: LIBRARIES => PRE LIBRARY FILTERING
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.lambda$0: Found library Movies (ID=3) with agent: tv.plex.agents.movie and 3078 item(s).
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.lambda$0: Found library TV Shows (ID=6) with agent: tv.plex.agents.series and 14724 item(s).
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.run: LIBRARIES => POST LIBRARY FILTERING
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.lambda$3: Will process library Movies (ID=3) with agent: tv.plex.agents.movie and 3078 item(s).
[INFO ] - 2021-09-05 21:41:58 @ ImdbDockerImplementation$ImdbBatchJob.lambda$3: Will process library TV Shows (ID=6) with agent: tv.plex.agents.series and 14724 item(s).
`````
