### ISSUE TITLE
USE_PLEX_SQLITE_BINARY_FOR_WRITE_ACCESS

### ISSUE THREAD

**Issue by mrjohnpoz** [mynttt/UpdateTool#71]
When I set this - I get this error

[ERROR] - 2021-09-21 12:22:43 @ ImdbDatabaseSupport.testPlexSqliteBinaryVersion: Checking Plex SQLite version took more than 1s... Likely invalid binary supplied @ /usr/app/plexsqlitedriver/Plex SQLite. Exiting tool...

Running on synology dsm7, with plex 1.24.3.5033

The sqlite is located here from my understanding - which have used..

/var/packages/PlexMediaServer/target/Plex\ SQLite

I have used it with this command to remove rotten tomato reviews

/var/packages/PlexMediaServer/target/Plex\ SQLite com.plexapp.plugins.library.db "DELETE FROM taggings WHERE extra_data LIKE '%rotten%'"

running 1.6.1 of the tool
[INFO ] - 2021-09-21 12:22:40 @ Main.main: Running version: 1.6.1

**Comment by mynttt** [comment]
With the new version there should be an embedded stripped down Plex within the container that's why it's showing this path. The path is docker internal.

Could you start the container without this environment variable so it doesn't shutdown then access the containers shell and execute this commands?

`dpkg -print -architecture`

`ls -l /usr/app/plexsqlitedriver`

**Comment by mrjohnpoz** [comment]
root@confident_perlman:/config# dpkg --print-architecture                                                                                                                         
amd64                                                                                                                                                                             
root@confident_perlman:/config# ls -l /usr/app/plexsqlitedriver                                                                                                                   
total 17504                                                                                                                                                                       
-rwxr-xr-x 1 root root 17909344 Sep 14 16:34 'Plex Media Server'                                                                                                                  
-rwxr-xr-x 1 root root    10680 Sep 14 16:09 'Plex SQLite'                                                                                                                        
drwxr-xr-x 1 root root     1948 Sep 20 22:17  lib                                                                                                                                 
root@confident_perlman:/config#

**Comment by mynttt** [comment]
Looks like it should work in theory. Can you try to run this on the container and post the output?

`echo "select sqlite_version();" | "/usr/app/plexsqlitedriver/Plex SQLite")`

**Comment by mrjohnpoz** [comment]
root@confident_perlman:/config# echo "select sqlite_version();" | "/usr/app/plexsqlitedriver/Plex SQLite"                                                                         
3.35.5

**Comment by mynttt** [comment]
Guess the timeout of 1s is too tightly set. I'll bump it to 10s and push an update.

**Comment by mrjohnpoz** [comment]
Sweet - let me know when up and will try right away.

**Comment by mynttt** [comment]
Try it now!

**Comment by mrjohnpoz** [comment]
Yeah that seems to have fixed it - but nothing to actually update at this time ;)

[INFO ] - 2021-09-21 13:13:04 @ ImdbDatabaseSupport.testPlexSqliteBinaryVersion: Plex SQLite binary version: 3.35.5 | COMPILER=clang-11.0.1 | ENABLE_COLUMN_METADATA | ENABLE_FTS3 | ENABLE_FTS3_PARENTHESIS | ENABLE_ICU | ENABLE_RTREE | ENABLE_UNLOCK_NOTIFY | MAX_EXPR_DEPTH=2048 | OMIT_DEPRECATED | THREADSAFE=1 |

**Comment by mynttt** [comment]
It went okay haha! The exam is pretty hard but since I managed to finish all exercises I should be able to pass! It is kind of an pass first and care about marks later exam =D
