### ISSUE TITLE
Gui "problems"

### ISSUE THREAD

**Issue by sucr4m** [mynttt/UpdateTool#72]
Gui wont start if capabilities is left empty
[ERROR] - 2021-10-14 01:53:58 @ ImdbDockerImplementation.bootstrap: Invalid CAPABILITIES value: Capabilities

Opt in for libraries using the new tv show agent doesnt save the ID after closing. 

(am i doing this right?)

**Comment by mynttt** [comment]
Looks like a bug I'll fix this soon.

**Comment by mynttt** [comment]
Are you sure the field is empty? In my version it works very well.

This screen has the value "Capabilities" that matches your error report.

![grafik](https://user-images.githubusercontent.com/22261092/144494028-370e756c-8be9-401d-ab9d-e04b9b172841.png)

And this screen has an empty field which allows the tool to start.

![grafik](https://user-images.githubusercontent.com/22261092/144494200-f4f0623e-a6f0-4a1f-81ed-25087bff4a05.png)

Has this been solved or you still have the issues and if so can you create a screen like the first one and share it here? Also make sure you use the newest version of the GUI (v.1.0.5).
