### ISSUE TITLE
Autostart GUI

### ISSUE THREAD

**Issue by crafty35a** [mynttt/UpdateTool#74]
Is there a way to auto-start the GUI on Windows? I added a shortcut to my startup folder, which does launch the GUI. But I still have to manually press the "Start" button within the GUI to kick it off. My goal is simply to have it launch with Windows and run every N hours.

**Comment by mynttt** [comment]
Hi! I will make sure to implement this the next days. I'll add a switch that causes the GUI to start UpdateTool on opening and minimize immediatly so you can just add the jar to your windows autostart.

**Comment by mynttt** [comment]
Functionality is now implemented with g1.0.6 => https://github.com/mynttt/UpdateTool/releases/tag/g1.0.6
