### ISSUE TITLE
database locked - warn in log.

### ISSUE THREAD

**Issue by mrjohnpoz** [mynttt/UpdateTool#76]
So I just noticed this.. My plex was updated recently to 1.25.0.5246, running on synology ds918+

[WARN ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.internalBatchUpdateOverPlexSqliteBinary: Update via Plex SQLite binary call produced potential error messages. Please contact the author of the tool with this output:
[WARN ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.internalBatchUpdateOverPlexSqliteBinary: Error: near line 2: database is locked | Error: near line 3: database is locked | Error: near line 4: database is locked | Error: near line 5: database is locked | Error: near line 6: database is locked | Error: near line 7: database is locked | Error: near line 8: database is locked | Error: near line 9: database is locked | Error: near line 10: database is locked | Error: near line 11: database is locked | Error: near line 12: database is locked | Error: near line 13: database is locked | Error: near line 14: database is locked | Error: near line 15: database is locked | Error: near line 16: database is locked | Error: near line 17: database is locked |
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 23: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 24: database is locked
[WARN ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.internalBatchUpdateOverPlexSqliteBinary: ==================================================
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.requestBatchUpdateOf: Running batch update for 46 item(s) with old plex agent.
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 25: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 26: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 27: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 28: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 29: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 30: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 31: database is locked
[INFO ] - 2021-11-22 14:29:18 @ ImdbDatabaseSupport.lambda$internalBatchUpdateOverPlexSqliteBinary$2: Error: near line 32: database is locked

Any info you need please just ask..

**Comment by mrjohnpoz** [comment]
Hmmm - just stop and restarted the docker.. And now all looks good updated lots of stuff..

**Comment by mynttt** [comment]
The database stuff is really strange. Is still everything working well? I will update the Plex version today that is used within the docker just as a precaution.. the entire database interaction via the PlexDB is sadly really scuffed...

**Comment by mrjohnpoz** [comment]
Yeah its working - last time it ran
[INFO ] - 2021-12-02 15:35:27 @ ImdbPipeline.transformMetadata: Transforming 22 item(s)
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: Adjust rating: 8.5 -> 7.8 for The Outlaws
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB, TVDB) for: The Outlaws
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: The Outlaws
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: Adjust rating: null -> 6.7 for Day 2
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Day 2
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: Adjust rating: null -> 8.2 for Episode 4
[INFO ] - 2021-12-02 15:35:27 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Episode 4

I am running plex 1.25.1.5286 currently

**Comment by mynttt** [comment]
Yeah I updated the dockers internal Plex Sqlite binary to 1.25 just in case yesterday evening too.

Maybe your error was because the database was busy. If it happens more often it's probably a good idea to not shutdown but just wait in that case.

**Comment by mrjohnpoz** [comment]
I have noticed the docker crashes ever now and then..

I get these email alert
[nas.local.lan] Docker container confident_perlman stopped unexpectedly

Not all that often - last one was 11/12, and before that 11/7 etc.. 

Not exactly sure what I was doing, checking if something had been update, or skipped because it wasn't showing imdb rating..

Quite well just could of been db busy for sure, I take it was that because after restart a bit later it worked fine.  Just noticed in the log that it said to bring to your attention ;)  And once I restarted the docker all was good, db prob finished whatever was going on.

I normally don't give it a 2nd thought as it just works.. But rare I get those emails and have to restart the docker..

**Comment by mrjohnpoz** [comment]
I just tried updating to the latest docker, and it won't start now.. Get this error in docker

standard_init_linux.go:230: exec user process caused: exec format error

Going to try and roll it back.

**Comment by mrjohnpoz** [comment]
Oh the previous versions don't seem to be available - shit.. Currently down it just doesn't start.

**Comment by mynttt** [comment]
Okay this is a general docker issue, probably the bash script for the entry file got messed up or something

**Comment by mynttt** [comment]
Yeah it is working again, just pull the update. Looks like something screwed up yesterday in the multi-arch build.

**Comment by mynttt** [comment]
> I have noticed the docker crashes ever now and then..
> 
> I get these email alert [nas.local.lan] Docker container confident_perlman stopped unexpectedly
> 
> Not all that often - last one was 11/12, and before that 11/7 etc..
> 
> Not exactly sure what I was doing, checking if something had been update, or skipped because it wasn't showing imdb rating..
> 
> Quite well just could of been db busy for sure, I take it was that because after restart a bit later it worked fine. Just noticed in the log that it said to bring to your attention ;) And once I restarted the docker all was good, db prob finished whatever was going on.
> 
> I normally don't give it a 2nd thought as it just works.. But rare I get those emails and have to restart the docker..

Yeah, unless that happens really frequently it's not worth investigating :D

**Comment by mrjohnpoz** [comment]
Yeah looks to be working now after redownload of image, yeah I agree the docker stopping is so rare not really worth looking into.. Was running fine since the 12 of october..
