### ISSUE TITLE
Library IDs don't save on close

### ISSUE THREAD

**Issue by dazedcrazy** [mynttt/UpdateTool#78]
When I add library IDs for the new TV show agent they don't save on close.  It makes the Autostart on GUI open setting useless. This is on Windows.

**Comment by mynttt** [comment]
That sounds like a bug when saving the configuration. Might have to patch that.

**Comment by dazedcrazy** [comment]
It was there before the new update, just didn't really bother me till now.

**Comment by mynttt** [comment]
Well there's no testing on the GUI so the actual testing is done by the users XD But good to know that there's an issue there

**Comment by mynttt** [comment]
Yeah the binding was not assigning the value on change. Fixed => https://github.com/mynttt/UpdateTool/releases/tag/g1.0.7
