### ISSUE TITLE
Option for verbose output in log

### ISSUE THREAD

**Issue by ookla-ariel-ride** [mynttt/UpdateTool#8]
I am still getting the 200 errors with accessing OMDB.  I am wondering if the UpdateTool is just getting stuck on a single item in my library and failing to return data from OMDB for that single item. Can you enable a flag that will output the item being processed by the OMDB API so I can see if there is some problem with it's metadata or entry in the Plex database?  thanks.

**Comment by mynttt** [comment]
Good idea. That really seems to be an OMDB issue, I will add a verbose flag tomorrow so you can investigate which item causes the OMDB issues.

**Comment by mynttt** [comment]
I implemented a way to change log levels at runtime but I find no use of adding any trace calls here. The error that you get is actually imporant and will now be logged this way:

```java
Logger.error("OMDB_API_FAIL := TITLE -> {} | IMDB_ID -> {} | GUID -> {} | RESPONSE_CODE -> {} | RESPONSE_BODY -> {}", item.title, item.imdbId, item.guid, response.statusCode(), response.body());
```

I hope there is enough useful information in it. Let me know what it spits out I'm curious as well.

**Comment by mynttt** [comment]
Closed due to inactivity.
