### ISSUE TITLE
Update also the Series Title

### ISSUE THREAD

**Issue by BetonMicha84** [mynttt/UpdateTool#80]
Hi,
first thanks a lot for this great update tool. Is ist possible to implement also an IMDB rating for the deries/series title in general not just the episodes? My Series are still tagged with TVDB/TMDB Ratings.
Thanks a lot!

**Comment by mynttt** [comment]
@BetonMicha84 In theory the tool should also update the ratings for series! Only Seasons can not be updated for now. Are you using the tool in combination with a TVDB v4 API key?

**Comment by BetonMicha84** [comment]
Im just using the Plex TV Show agent. Can I use TVDB v4 and the new tv show agend in combination?

**Comment by mynttt** [comment]
The tool has an environment variable named `TVDB_API_KEY` that can be filled with an API Key for the TVDB service. Sadly the key now appearently coasts 11$/year, but with this key the tool can match items in your database with TMDB ratings that previously only have an entry in the TVDB service.

You can however at least resolve this issue regarding TMDB matched items. Their API Keys are free and there are some instructions [here](https://www.themoviedb.org/documentation/api) on how to get one (would be a developer key in your case). You can then set the value of the enviornment variable `TMDB_API_KEY` with that key. UpdateTool can then match TMDB <=> IMDB items and thus update the ratings.

The main issue is that probably no IMDB IDs are saved by Plex in the background and only TMDB/TVDB ones - the tool can thus not operate on these IDs as it has no way to access the respective services to do an TMDB/TVDB <=> IMDB lookup which it needs to then associate the correct ratings.

Are you using this tool with the GUI or over Docker/Unraid?

**Comment by BetonMicha84** [comment]
Thanks a lot! This was very helpful. I will try to get an tmdb key first. I‘m using your docker image on unraid.

**Comment by BetonMicha84** [comment]
Now i got a TMDB API Key, but the Series are still not Updates, just the episodes...
Log seems fine

[INFO ] - 2021-12-26 23:14:53 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
[INFO ] - 2021-12-26 23:14:53 @ ImdbRatingDatasetFactory.readData: Reading data...
[INFO ] - 2021-12-26 23:14:54 @ ImdbRatingDatasetFactory.readData: 1198551 lines read.
[INFO ] - 2021-12-26 23:14:54 @ TmdbApiV3.<init>: Testing TMDB API (v3) key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[INFO ] - 2021-12-26 23:14:54 @ TmdbApiV3.<init>: Test passed. API Key is valid.
[WARN ] - 2021-12-26 23:14:54 @ NewPlexAgentToImdbResolvement.<init>: No TVDB fallback set. Will not resolve new plex agent items if they only have a TVDB id associated.

**Comment by mynttt** [comment]
@BetonMicha84 Glad it works =) It is a shame that TVDB went paywall... The good thing is that the resolvements are cached so if you ever stop using their service the tool will keep every resolved entry forever (unless deleted).

**Comment by mynttt** [comment]
@BetonMicha84 Are there still issues? Otherwise, I should maybe check what the tool actually does in the next weeks as I'm not actively using Plex at the moment, so I would not keep up with changes myself.

**Comment by BetonMicha84** [comment]
Thanks a lot for asking. I‘m using the tool everyday and I have access to tmdb & tvdb API. So everything works as it should. What else do you use instead? I also used jellyfin and emby but stayed on plex…

**Comment by mynttt** [comment]
Good to know! I asked because of your edit with the TMDB thingy - but seems like that resolved?

Well I'm still using Plex but I'm only rarely looking into it as I rarely watch any movies or TV shows at the moment ^^ So if there would ever be an issue with the tool not updating the ratings anymore I'd probably be the last to find out - altough I keep running the tool on my UnRaid server of course.
