### ISSUE TITLE
Movies are being processed but not TV shows

### ISSUE THREAD

**Issue by Avyayy** [mynttt/UpdateTool#83]
Its Showing 
“New TV Show Agent Library ID: 1 will not be processed by updatetool. Please register with environment with environment variable UNLOCK_FOR_NEW_TV_AGENT to unlock processing capabilities “

**Comment by mynttt** [comment]
Can you make a screenshot of your GUI settings? 

⚠**Censor your API Keys with Paint!** ⚠

**Comment by Avyayy** [comment]
I am sorry I didn’t see your previous answer on my post.
It works now by just typing 1
Previously i was typing the whole unlock—-
Thanks

also i want to ask is there a way to forcefully update some episodes which the tool can’t match

**Comment by mynttt** [comment]
Right now there is no way to do this because there has been no demand for it. But you could create a issue describing your problem and delivering sample data and once I have time I could implement this for you.
