### ISSUE TITLE
Custom episode order

### ISSUE THREAD

**Issue by Pluvical** [mynttt/UpdateTool#93]
Hello,

On some of my series I have episodes in a different order than what themoviedb/tvdb have on their websites. However, when I run UpdateTool, it can't recognize the custom episode order and just applies the imdb ratings under the assumption that the episodes are in tvdb/themoviedb order. Is there a way to use update tool with series that have custom episode orders, or is this not possible?

Thanks

**Comment by mynttt** [comment]
By default, it uses the `aired season / aired episode` order to do lookups, apparently there is also `DVD order` tho. Is that used by your library? Because then I could implement a flag that allows you to manually toggle the mode for certain libraries.

**Comment by Pluvical** [comment]
For certain series I've opted to use DVD order, but for most, I am using the library default (TVDB aired order, I believe). Being able to use the update tool with my DVD-ordered series would be amazing. Would every series in the library have to be set to DVD order for it to work properly, or would it be able to differentiate between which series use the DVD order and which series use the default order?

**Comment by mynttt** [comment]
@Pluvical 

I've found out that this data is stored for the show in the `extra_data` field i.e. `showOrdering=dvd`. So in theory it would be possible to detect these items and then supply this data when making a request to TVDB/TMDB. So you would not have to manually define which items have different behavior.

As it is a new feature I would implement it when I have time to look at it in detail. You could help me however by sending over your database so I could test against it per mail (marc@herschel.io). I would likely try to look at it in the next weeks.
