### ISSUE TITLE
Sort by critic rating not sorting by IMDB rating

### ISSUE THREAD

**Issue by MitjaHenner** [mynttt/UpdateTool#95]
After adding the tvdb api-key I have all the IMDB ratings showing for my shows (except Arcane for some reason) but when I sort by critic rating it looks like it's still sorting by the TMDB rating. Is there a way to change this, or do I have to edit the TMDB value manually to match the IMDB rating?

**Comment by xvvjt4** [comment]
Sort by "Audience Rating" in Plex and you're good.

**Comment by MitjaHenner** [comment]
Oh, I'm dumb, I thought audience rating was the star rating in Plex...
