### ISSUE TITLE
Error: a JNI error has occured, please check your installation and try again.

### ISSUE THREAD

**Issue by Scoits** [mynttt/UpdateTool#96]
Error: a JNI error has occured, please check your installation and try again.
A java exception has occured.

These 2 pop up when trying to open the file? got the most recent java installed? not sure what i need to do?

**Comment by mynttt** [comment]
Hi! Have you got the JDK from https://adoptium.net/ installed? If you try to click it, it might not work. But you could run the GUI with java -jar <name_of_jar.jar> and that should do it. I just tested it on Win 10 with Java 17 and it looked fine.
