### ISSUE TITLE
Unraid current integration 

### ISSUE THREAD

**Issue by ConnorEMacLean** [mynttt/UpdateTool#97]
Hello!

Saw a link to your project in a reddit post and thought it looked really cool!
A bit new to the whole scene so still running into some newb questions. 

In regards to installing in Unraid, I see it looks Template Repositories are since deprecated. 
https://forums.unraid.net/topic/118437-there-is-no-template-repositories-in-my-docker-setting-page/

A bit unsure now as how to add the template as I see have the ability to add the container but not sure how then to use the provided template https://github.com/mynttt/unraid-templates

Thanks!

**Comment by Reynieri** [comment]
do you have any luck running  this on unRaid ? I'm also looking to run this on unRaid.

**Comment by xbp13x** [comment]
Place the XML file in /boot/config/plugins/dockerMan/templates-user then it will show up when you click add container in the docker tab.

Heads up though, this bricked my database after running it. I think maybe PLEX has made some changes to the database and this is not compatible atm.

**Comment by ConnorEMacLean** [comment]
Thanks for the update and good to know about the potential issues with the database.
Sounds like I might be holding off for a little while and keep tabs here for future updates.
If you get your database back up and running and everything working properly xbp13x def would love to hear about it!

**Comment by mynttt** [comment]
Good to know that Unraid does not support template repositories anymore - I might try to have this tool added to their "app store". However as some of the DB issues still exist for a subset of users I'll likely hold off until the reason has been found.

**Comment by mynttt** [comment]
@ConnorEMacLean @xbp13x Maybe the solution in https://github.com/mynttt/UpdateTool/issues/101#issuecomment-1426998755 helps with the corruption issue!

**Comment by ConnorEMacLean** [comment]
Awesome! Thanks for the heads up prob will give this a whirl this weekend.

**Comment by mynttt** [comment]
@ConnorEMacLean Sadly that is not the solution as it caused corruption again during the day for him, but if you look at the bottom of this issue you'll see that I added a docker tag :test today that had some changes and did not lead to corruption for the issue reporter.

We'll observe it over the days now and if the changes don't cause any corruptions anymore I'll update the main tool and docker and then you could try it out.

I'll notify you when if it's safe to use.
