### ISSUE TITLE
Run every 24hrs seems to be a more sane default

### ISSUE THREAD

**Issue by burkasaurusrex** [mynttt/UpdateTool#98]
I've been playing around with the IMDb interfaces for the last month and discovered that the `title.ratings.tsv.gz` file is only exported once a day (around 13:20 UTC). Given there is only one export a day, it might make more sense to set the defaults to 24hrs?

Normally to capture that update, you'd just cron with some delay, but there's something weird happening with IMDb's CDN. The availability of the file gets a little more delayed every day (I suspect there's a TTL setting that is set wrong). So, if there was a desire to make this more exact, UpdateTool could do a `HEAD` call to the interface every `n` hours to see if the `etag` header (MD5 of the file) has changed. Then if it's changed, download the file and run the full update.

**Comment by mynttt** [comment]
I have bumped it up to 24h as I agree that it makes sense! The `HEAD` solution sounds great, but I'm not able to implement it as I lack the time, and it would add some more complexity to potentially break in the future. Thanks for your effort and suggestion!
